FROM php:7.1.0RC3-fpm

RUN apt-get update
RUN apt-get install -y git cron  libmcrypt-dev nodejs nano
RUN docker-php-ext-install mcrypt mbstring tokenizer mysqli pdo_mysql
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer
VOLUME ["/app/www:/app/www"]
